//
//  MainRouter.swift
//  SampleProject
//
//  Created by 植田裕作 on 2018/10/08.
//  Copyright © 2018年 Yusaku Ueda. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class MainRouter: MainWireframeProtocol {

    // MARK: Properties

    private weak var viewController: MainViewController?

    /// Factory method
    static func createModule() -> MainViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MainViewController(nibName: nil, bundle: nil)
        let router = MainRouter()
        let presenter = MainPresenter(interface: view, router: router)

        view.presenter = presenter
        router.viewController = view

        return view
    }

    // MARK: - Life cycle

    private init() {
    }

    deinit {
    }

    // MARK: - WireframeProtocol
}
