//
//  LoginPresenter.swift
//  SampleProject
//
//  Created by 植田裕作 on 2018/10/08.
//  Copyright © 2018年 Yusaku Ueda. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class LoginPresenter: LoginPresenterProtocol {

    // MARK: Properties

    private weak var view: LoginViewProtocol?
    private let router: LoginWireframeProtocol

    // MARK: - Life cycle

    init(interface: LoginViewProtocol, router: LoginWireframeProtocol) {
        self.view = interface
        self.router = router
    }

    deinit {
    }

    // MARK: - PresenterProtocol

    // MARK: ViewController -> Presenter

    func viewDidLoad() {
    }

    func viewWillAppear(_ animated: Bool) {
    }

    func viewDidAppear(_ animated: Bool) {
    }

    func viewWillDisappear(_ animated: Bool) {
    }

    func viewDidDisappear(_ animated: Bool) {
    }

    func onLoginButton() {
    }

    // MARK: Presenter -> ViewController
}
