//
//  SplashPresenter.swift
//  SampleProject
//
//  Created by 植田裕作 on 2018/10/10.
//  Copyright © 2018年 Yusaku Ueda. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class SplashPresenter: SplashPresenterProtocol {

    // MARK: Properties

    private weak var view: SplashViewProtocol?
    private let router: SplashWireframeProtocol

    // MARK: - Life cycle

    init(interface: SplashViewProtocol, router: SplashWireframeProtocol) {
        self.view = interface
        self.router = router
    }

    deinit {
    }

    // MARK: - PresenterProtocol

    // MARK: ViewController -> Presenter

    func viewDidLoad() {
    }

    func viewWillAppear(_ animated: Bool) {
    }

    func viewDidAppear(_ animated: Bool) {
        let vc = MainRouter.createModule()
        let navi = UINavigationController(rootViewController: vc)
        AppDelegate.shared.appViewController.setCurrentViewController(navi, animated: true)
    }

    func viewWillDisappear(_ animated: Bool) {
    }

    func viewDidDisappear(_ animated: Bool) {
    }

    // MARK: Presenter -> ViewController
}
