//
//  LoginRouter.swift
//  SampleProject
//
//  Created by 植田裕作 on 2018/10/08.
//  Copyright © 2018年 Yusaku Ueda. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Model

final class LoginRouter: LoginWireframeProtocol {

    // MARK: Properties

    private weak var viewController: LoginViewController?

    /// Factory method
    static func createModule() -> LoginViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoginViewController()
        let router = LoginRouter()
        let presenter = LoginPresenter(interface: view, router: router)
        let repository = AccountRepository.shared
        let usecase = LoginUsecase()

        view.presenter = presenter
        router.viewController = view
        presenter.loginUsecase = usecase
        usecase.accountRepository = repository

        return view
    }

    // MARK: - Life cycle

    private init() {
    }

    deinit {
    }

    // MARK: - WireframeProtocol

    /// ログイン画面を閉じる
    func closeLogin() {
        viewController?.navigationController?.popViewController(animated: true)
    }

}
