//
//  WebViewViewController.swift
//  SampleProject
//
//  Created by 植田裕作 on 2018/11/06.
//  Copyright © 2018年 Yusaku Ueda. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Common
import Model
import WebKit

final class WebViewViewController: UIViewController, WebViewViewProtocol {

    // MARK: - IBOutlet

    @IBOutlet weak var navigationView: UIView!
    @IBOutlet weak var backButton: UIButton!
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var webView: WKWebView!
    @IBOutlet weak var toolBar: UIToolbar!
    @IBOutlet weak var backwardButton: UIBarButtonItem!
    @IBOutlet weak var forwardButton: UIBarButtonItem!
    @IBOutlet weak var refreshButton: UIBarButtonItem!
    @IBOutlet weak var activityIndicatorView: UIActivityIndicatorView!

    // MARK: Properties

	var presenter: WebViewPresenterProtocol?
    /// 遅れて読み込ませるリクエスト
    private var delayLoadRequest: URLRequest?

    // MARK: - Life cycle

    convenience init() {
        self.init(nibName: nil, bundle: Bundle(for: type(of: self)))
    }

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    deinit {
        log.debug()
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        if let request = delayLoadRequest {
            // startLoadRequestが先に呼ばれていれば保持していたリクエストをここで読み込む
            webView.load(request)
            self.delayLoadRequest = nil
        }

        presenter?.viewDidLoad()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        presenter?.viewWillAppear(animated)
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        presenter?.viewDidAppear(animated)
    }

    override func viewWillDisappear(_ animated: Bool) {
        presenter?.viewWillDisappear(animated)
        super.viewWillDisappear(animated)
    }

    override func viewDidDisappear(_ animated: Bool) {
        presenter?.viewDidDisappear(animated)
        super.viewDidDisappear(animated)
    }

    // MARK: Rotate

    // MARK: Override

    // MARK: - ViewProtocol

    /// 読み込み開始する
    func startLoadRequest(_ request: URLRequest) {
        if isViewLoaded {
            // すでにviewDidLoadが呼ばれていれば、ここで読み込み
            webView.load(request)
        } else {
            // まだviewDidLoadが呼ばれていなければ、あとで読み込むために保持する
            self.delayLoadRequest = request
        }
    }

    /// 前の履歴に進む
    func goToBackward() {
        if webView.canGoBack {
            webView.goBack()
        }
    }

    /// 次の履歴に進む
    func goToForward() {
        if webView.canGoForward {
            webView.goForward()
        }
    }

    /// 再読み込みする
    func reloadPage() {
        webView.reload()
    }
}

// MARK: - Methods
// MARK: - Actions

extension WebViewViewController {
    /// 戻るボタンが押された時
    @IBAction func onBackButton(_ sender: UIButton) {
        presenter?.onBackButton()
    }

    /// 前へ戻るボタンが押された時
    @IBAction func onBackwardButton(_ sender: UIBarButtonItem) {
        presenter?.onBackwardButton()
    }

    /// 次へ進むボタンが押された時
    @IBAction func onForwardButton(_ sender: UIBarButtonItem) {
        presenter?.onForwardButton()
    }

    /// 更新ボタンが押された時
    @IBAction func onRefreshButton(_ sender: UIBarButtonItem) {
        presenter?.onRefreshButton()
    }
}

// MARK: - Notifications
